---
- name: Deploy Cloudflared Secrets
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # You need to provide the path to your tunnel credentials file
    # This should be the path to your ~/.cloudflared/<tunnel ID>.json file
    tunnel_credentials_path: "{{ playbook_dir }}/../secrets/tunnel-credentials.json"
  tasks:
    - name: Create networking namespace (if not exists)
      kubernetes.core.k8s:
        name: networking
        api_version: v1
        kind: Namespace
        state: present

    - name: Check if tunnel credentials file exists
      stat:
        path: "{{ tunnel_credentials_path }}"
      register: tunnel_creds_file

    - name: Create tunnel credentials secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: tunnel-credentials
            namespace: networking
          type: Opaque
          data:
            credentials.json: "{{ lookup('file', tunnel_credentials_path) | b64encode }}"
        state: present
      when: tunnel_creds_file.stat.exists

    - name: Warning message if credentials file not found
      debug:
        msg: |
          WARNING: Tunnel credentials file not found at {{ tunnel_credentials_path }}
          Please ensure you have:
          1. Created a cloudflare tunnel: cloudflared tunnel create <tunnel-name>
          2. Copied the credentials file to {{ tunnel_credentials_path }}
          3. Updated the tunnel name in the main cloudflared config
      when: not tunnel_creds_file.stat.exists 