---
- name: Install Argo CD using Helm
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Add ArgoProj Helm repository
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm
        state: present
    
    - name: Create devops namespace
      kubernetes.core.k8s:
        name: devops
        api_version: v1
        kind: Namespace
        state: present
    
    - name: Install ArgoCD using Helm chart
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        chart_version: "8.0.17"
        release_namespace: devops
        create_namespace: true
        state: present
        timeout: 10m0s
        wait: true
        values:
          global:
            domain: argocd-server.devops.svc.home-hk1-cluster.orbb.li
          configs:
            cm:
              oidc.config: |
                name: Keycloak
                issuer: https://keycloak-lab.orbb.li/realms/orbb.li
                clientID: argocd
                clientSecret: $oidc.keycloak.clientSecret
                requestedScopes: 
                  - openid
                  - profile
                  - email
                  - groups
        # values:
        #   configs:
        #     params:
        #       server.disable.auth: true
        #   server:
        #     service:
        #       type: ClusterIP 

# kubectl -n devops get secret argocd-initial-admin-secret -o json | jq -r .data.password | base64 -d
# https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/