---
- name: Install Monitoring Storage Stack (Prometheus, Loki, Grafana)
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Add Prometheus Community Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        state: present

    - name: Add Bitnami Helm repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        state: present

    - name: Create observability namespace
      kubernetes.core.k8s:
        name: observability
        api_version: v1
        kind: Namespace
        state: present

    - name: Read Grafana OAuth client secret from file
      slurp:
        src: "{{ playbook_dir }}/../secrets/grafana-oauth-secret"
      register: grafana_oauth_secret_file

    - name: Create Grafana OAuth secret in Kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: grafana-oauth-secret
            namespace: observability
          type: Opaque
          data:
            client-secret: "{{ grafana_oauth_secret_file.content }}"

    - name: Install kube-prometheus-stack (Prometheus + Grafana) using Helm chart
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: observability
        create_namespace: false
        state: present
        timeout: 15m0s
        wait: true
        values_files:
          - "{{ playbook_dir }}/monitoring-values/grafana-values.yaml"

    - name: Install Loki using Helm chart
      kubernetes.core.helm:
        name: loki
        chart_ref: bitnami/grafana-loki
        release_namespace: observability
        create_namespace: false
        state: present
        timeout: 10m0s
        wait: true
        values_files:
          - "{{ playbook_dir }}/monitoring-values/loki-values.yaml"

    - name: Display access information
      debug:
        msg: |
          Monitoring stack installed successfully!
          
          Components installed:
          - Prometheus (metrics collection and storage)
          - Grafana (visualization dashboard)
          - Loki (log aggregation and storage)
          
          Next steps:
          1. Configure Grafana OAuth secret if not already done:
             kubectl -n observability create secret generic grafana-oauth-secret --from-literal=client-secret='your-keycloak-client-secret'
          
          2. Access Grafana at: https://grafana-lab.orbb.li
          
          3. Prometheus should be accessible via Grafana or directly through the service
          
          4. Loki will be ready to receive logs from log shippers 