alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy

controller:
  type: daemonset
  
  # Pod settings
  podAnnotations: {}
  
  # Extra volume mounts
  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true

# Extra volumes
extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log

service:
  enabled: true
  type: ClusterIP

serviceMonitor:
  enabled: true

rbac:
  create: true

serviceAccount:
  create: true
  name: alloy

# Tolerate all taints to run on every node
tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists