apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops

commonLabels:
  app.kubernetes.io/name: argocd-ui
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/component: ui

resources:
- deployment.yaml
- service.yaml
- configmap.yaml