# Keycloak database connection secret
# Password will be patched by Ansible
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: iam
type: Opaque
stringData:
  username: keycloak
  password: POSTGRES_PASSWORD_PLACEHOLDER