apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.10.0
    chart: alloy
    helm:
      releaseName: alloy
      valuesFile: /home/eli/workbench/homelab/kubernetes/apps/observability/alloy/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true