apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.24.0
    chart: loki
    helm:
      releaseName: loki
      values: |
        # Global settings for custom cluster domain
        global:
          dnsService: "kube-dns"
          dnsNamespace: "kube-system"
          clusterDomain: "home-hk1-cluster.orbb.li"
        
        # Loki Stack Values
        loki:
          auth_enabled: false
          
          commonConfig:
            replication_factor: 1
          
          storage:
            type: filesystem
            
          persistence:
            enabled: true
            storageClassName: k8s-csi
            size: 50Gi
            
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h

          limits_config:
            retention_period: 30d
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            max_cache_freshness_per_query: 10m
            split_queries_by_interval: 24h

          compactor:
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
            delete_request_store: filesystem

        # Deploy single binary mode for simplicity
        deploymentMode: SingleBinary
        
        # Disable read/write/backend when using SingleBinary mode
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: k8s-csi
            size: 50Gi
          extraArgs:
            - -config.expand-env=true
            - -ingester.wal-enabled=false
          extraEnv:
            - name: LOKI_REPLICATION_FACTOR
              value: "1"

        # Promtail for log collection
        promtail:
          enabled: false  # We'll use Alloy instead for unified collection

        # Grafana
        grafana:
          enabled: false  # Deploy separately

        # Gateway
        gateway:
          enabled: true
          ingress:
            enabled: false
          nginxConfig:
            resolver: "kube-dns.kube-system.svc.home-hk1-cluster.orbb.li"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m