apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: iam
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  username: keycloak
  password: keycloak-postgres-pass-changeme