apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iam

resources:
  # Install Keycloak Operator from upstream
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.7/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.7/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.7/kubernetes/kubernetes.yml
  
  # Keycloak instance and configuration
  - keycloak-instance.yaml
  - keycloak-ingress.yaml
  - keycloak-db-secret.yaml

patches:
  # Patch the operator deployment to use less resources for homelab
  - target:
      kind: Deployment
      name: keycloak-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi