apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

resources:
- glm-spark1.yaml
- glm-spark2.yaml
- nomad-hk2.yaml

labels:
- pairs:
    app.kubernetes.io/managed-by: argocd
  includeSelectors: false
