apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: home-hk1-cluster-connector
  namespace: networking
spec:
  hostname: home-hk1-cluster-connector
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "10.42.0.0/16"
      - "10.43.0.0/16"
