---
- name: Setup kubectl config and install kubectl/helm
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Create .kube directory
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Create certs directory
      file:
        path: "{{ ansible_env.HOME }}/.kube/certs"
        state: directory
        mode: '0755'

    - name: Fetch k3s.yaml from remote
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/k3s.yaml
        flat: yes
      delegate_to: home-hk1-pi1
      become: true
      vars:
        ansible_user: o
        ansible_connection: ssh
        ansible_host: 192.168.88.41

    - name: Fetch k3s CA cert from remote
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/tls/server-ca.crt
        dest: "{{ ansible_env.HOME }}/.kube/certs/k3s-ca.crt"
        flat: yes
      delegate_to: home-hk1-pi1
      become: true
      vars:
        ansible_user: o
        ansible_connection: ssh
        ansible_host: 192.168.88.41

    - name: Replace server IP in k3s.yaml
      ansible.builtin.replace:
        path: /tmp/k3s.yaml
        regexp: 'server: https://(0.0.0.0|127.0.0.1):'
        replace: 'server: https://192.168.88.41:'

    - name: Update certificate-authority in k3s.yaml
      ansible.builtin.replace:
        path: /tmp/k3s.yaml
        regexp: 'certificate-authority-data: .*'
        replace: 'certificate-authority: {{ ansible_env.HOME }}/.kube/certs/k3s-ca.crt'

    - name: Copy modified config to .kube/config
      ansible.builtin.copy:
        src: /tmp/k3s.yaml
        dest: "{{ ansible_env.HOME }}/.kube/config"
        mode: '0600'
        remote_src: yes

    - name: Get latest kubectl version
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: kubectl_version

    - name: Download kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl"
        dest: /tmp/kubectl
        mode: '0755'

    - name: Install kubectl
      become: true
      ansible.builtin.copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
        remote_src: yes

    - name: Download and install Helm
      become: true
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/k3s.yaml
        - /tmp/kubectl
