---
- name: Install Tailscale Operator in Kubernetes
  hosts: localhost
  connection: local
  vars:
    tailscale_k8s_op_oauth_client_id: "{{ hostvars['sd1']['tailscale_k8s_op_oauth_client_id'] }}"
    tailscale_k8s_op_oauth_client_secret: "{{ hostvars['sd1']['tailscale_k8s_op_oauth_client_secret'] }}"
    tailscale_k8s_op_hostname: "{{ hostvars['sd1']['tailscale_k8s_op_hostname'] }}"
  tasks:
    - name: Add Tailscale Helm repository
      kubernetes.core.helm_repository:
        name: tailscale
        repo_url: https://pkgs.tailscale.com/helmcharts

    - name: Install Tailscale Operator
      kubernetes.core.helm:
        name: tailscale-operator
        chart_ref: tailscale/tailscale-operator
        release_namespace: networking
        create_namespace: true
        wait: true
        values:
          oauth:
            clientId: "{{ tailscale_k8s_op_oauth_client_id }}"
            clientSecret: "{{ tailscale_k8s_op_oauth_client_secret }}"
          operatorConfig:
            hostname: "{{ tailscale_k8s_op_hostname }}"

    - name: Apply Tailscale Connector configuration
      kubernetes.core.k8s:
        state: present
        src: k8s_configs/ts-connector.yaml


