# Loki Stack Values
loki:
  auth_enabled: false
  
  storage:
    type: filesystem
    
  persistence:
    enabled: true
    storageClassName: k8s-csi
    size: 50Gi
    
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  limits_config:
    retention_period: 30d
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 24h

  compactor:
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150

# Deploy single binary mode for simplicity
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: k8s-csi
    size: 50Gi

# Promtail for log collection
promtail:
  enabled: false  # We'll use Alloy instead for unified collection

# Grafana
grafana:
  enabled: false  # Deploy separately

# Gateway
gateway:
  enabled: true
  ingress:
    enabled: false