apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
- namespace.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- keycloak-deployment.yaml
- keycloak-service.yaml
- keycloak-ingress.yaml

# Note: Secrets are created by Ansible, not Kustomize
# Removing secretGenerator to avoid duplicate secrets

configMapGenerator:
- name: keycloak-config
  literals:
  - KC_DB=postgres
  - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
  - KC_HOSTNAME=keycloak.orbb.li
  - KC_PROXY=edge
  - KC_HTTP_ENABLED=true
  - KC_HEALTH_ENABLED=true
  - KC_METRICS_ENABLED=true