# Pyroscope configuration for continuous profiling
# Standalone single-instance deployment
#
# TODO: Future enhancement - Add S3 backend using MinIO/SeaweedFS
# See docs/TODO-s3-abstraction.md for S3 abstraction strategy
# This would enable distributed mode and unlimited storage

# Disable MinIO - using local storage for now
minio:
  enabled: false

# Disable Alloy - will be configured in playbook 07
alloy:
  enabled: false

# Disable Grafana Agent
agent:
  enabled: false

# Main Pyroscope configuration
pyroscope:
  # Single binary mode - all components in one container
  # This is simpler and sufficient for homelab use
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 50Gi
      storageClass: k8s-csi  # Using default storage class
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 512Mi
        cpu: 100m
  
  # Structured configuration for Pyroscope
  structuredConfig:
    # Server configuration
    server:
      http_listen_port: 4040
      log_level: info
    
    # Storage configuration - filesystem for single instance
    storage:
      backend: filesystem
      filesystem:
        directory: /data
    
    # Distributor configuration for receiving profiles
    distributor:
      ring:
        kvstore:
          store: inmemory
    
    # Ingester configuration
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    
    # Query limits
    limits:
      max_query_lookback: 720h  # 30 days
      max_query_length: 720h    # 30 days
      max_query_parallelism: 30
      max_flamegraph_nodes_default: 16000
      max_nodes_render: 16000
    
    # Analytics
    analytics:
      reporting_enabled: false

# Service configuration
service:
  type: ClusterIP
  port: 4040
  targetPort: 4040
  annotations: {}

# ServiceMonitor for Prometheus scraping (if needed)
serviceMonitor:
  enabled: false

# Ingress configuration (disabled for homelab with Tailscale)
ingress:
  enabled: false

# Pod annotations for profile collection by Alloy (when configured)
podAnnotations:
  profiles.grafana.com/memory.scrape: "true"
  profiles.grafana.com/memory.port: "4040"
  profiles.grafana.com/cpu.scrape: "true"
  profiles.grafana.com/cpu.port: "4040"
  profiles.grafana.com/goroutine.scrape: "true"
  profiles.grafana.com/goroutine.port: "4040"