# Pyroscope configuration for continuous profiling
# Standalone single-instance deployment
#
# TODO: Future enhancement - Add S3 backend using MinIO/SeaweedFS
# See docs/TODO-s3-abstraction.md for S3 abstraction strategy
# This would enable distributed mode and unlimited storage

# Disable MinIO - using local storage for now
minio:
  enabled: false

# Disable Alloy - will be configured in playbook 07
alloy:
  enabled: false

# Disable Grafana Agent (legacy, replaced by Alloy)
agent:
  enabled: false

# Main Pyroscope configuration
pyroscope:
  # Single replica for homelab
  replicaCount: 1
  
  # Persistence configuration
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 50Gi
    storageClassName: k8s-csi
  
  # Pod annotations for profile collection by Alloy (when configured in playbook 07)
  podAnnotations:
    profiles.grafana.com/memory.scrape: "true"
    profiles.grafana.com/memory.port: "4040"
    profiles.grafana.com/cpu.scrape: "true"
    profiles.grafana.com/cpu.port: "4040"
    profiles.grafana.com/goroutine.scrape: "true"
    profiles.grafana.com/goroutine.port: "4040"
  
  # Components configuration - empty means single-binary mode
  components: {}
  
  # Pyroscope configuration using structuredConfig
  # This gets merged with the default config
  structuredConfig:
    # Storage - using filesystem for single instance
    storage:
      backend: filesystem
      filesystem:
        directory: /data
    
    # Server configuration
    server:
      http_listen_port: 4040
      log_level: info
    
    # Query limits
    limits:
      max_query_lookback: 720h  # 30 days
      max_query_length: 720h    # 30 days
    
    # Disable analytics reporting
    analytics:
      reporting_enabled: false

# ServiceMonitor for Prometheus scraping (if needed later)
serviceMonitor:
  enabled: false

# Ingress disabled (using Tailscale for access)
ingress:
  enabled: false