apiVersion: v1
kind: Namespace
metadata:
  name: observability-host
  labels:
    name: observability-host
    # Privileged enforcement to allow node-exporter to access host resources
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged