apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-status
  namespace: gitops
  labels:
    app.kubernetes.io/name: infra-status
    app.kubernetes.io/part-of: observability
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: default

  source:
    repoURL: https://github.com/orbli/homelab.git
    targetRevision: master
    path: kubernetes/manifests/infra-status
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: infra-status

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
