apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-alloy
  namespace: gitops
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: observability
  annotations:
    argocd.argoproj.io/sync-wave: "30"  # After Loki
spec:
  project: default
  
  source:
    repoURL: https://github.com/orbli/homelab.git
    targetRevision: master
    path: kubernetes/manifests/alloy
    kustomize: {}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false  # Namespace should already exist
    - ServerSideApply=true   # Use server-side apply for CRDs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m