apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-namespace
  namespace: gitops
  labels:
    app.kubernetes.io/name: cloudflared-namespace
    app.kubernetes.io/part-of: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "30"  # After Keycloak
spec:
  project: default
  
  source:
    repoURL: https://github.com/orbli/homelab.git
    targetRevision: master
    path: kubernetes/apps/cloudflared/namespace
    kustomize: {}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m