apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops

resources:
# ArgoCD Self-hosting
- argocd-self-host-app.yaml    # ArgoCD Core managing itself

# Keycloak Applications (in order of sync wave)
- keycloak-namespace-app.yaml  # Wave 10: Namespace only
- keycloak-operator-app.yaml   # Wave 20: Operator and PostgreSQL
# Note: Secrets managed by Ansible, not GitOps
# Note: Realms managed by Ansible, not GitOps

# Cloudflared Applications (in order of sync wave)
- cloudflared-namespace-app.yaml     # Wave 30: Namespace only
- cloudflared-deployment-app.yaml    # Wave 40: Deployment and ConfigMap
# Note: Tunnel credentials managed by Ansible between namespace and deployment

# Observability Stack - App of Apps pattern
- observability-stack-app.yaml        # Parent app managing all observability components
# Individual apps now managed by the parent app-of-apps