# Grafana Alloy Configuration for ArgoCD deployment
# This collects logs, metrics, and traces from all pods

alloy:
  configMap:
    create: true
    content: |
      // ====== LOG COLLECTION ======
      // Discover Kubernetes pods for logs
      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      // Relabel to add metadata for logs
      discovery.relabel "pods" {
        targets = discovery.kubernetes.pods.targets
        
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }
        
        rule {
          source_labels = ["__meta_kubernetes_pod_node_name"]
          target_label  = "node"
        }
      }
      
      // Collect logs using Kubernetes API
      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.pods.output
        forward_to = [loki.write.default.receiver]
      }
      
      // Write logs to Loki
      loki.write "default" {
        endpoint {
          url = "http://loki.observability.svc.home-hk1-cluster.orbb.li:3100/loki/api/v1/push"
        }
      }
      
      // ====== TRACE COLLECTION (OTEL) ======
      // OTLP receiver for traces
      otelcol.receiver.otlp "default" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }
        
        http {
          endpoint = "0.0.0.0:4318"
        }
        
        output {
          traces  = [otelcol.processor.batch.default.input]
        }
      }
      
      // Batch processor for better performance
      otelcol.processor.batch "default" {
        output {
          traces = [otelcol.processor.k8sattributes.default.input]
        }
      }
      
      // Add Kubernetes attributes to traces
      otelcol.processor.k8sattributes "default" {
        extract {
          metadata = ["k8s.namespace.name", "k8s.pod.name", "k8s.deployment.name", "k8s.node.name"]
        }
        
        output {
          traces = [otelcol.exporter.otlp.tempo.input]
        }
      }
      
      // Export traces to Tempo Distributor
      otelcol.exporter.otlp "tempo" {
        client {
          endpoint = "tempo-distributor.observability.svc.home-hk1-cluster.orbb.li:4317"
          tls {
            insecure = true
          }
        }
      }
      
      // Profile collection discovery
      discovery.kubernetes "pods" {
        role = "pod"
        namespaces {
          own_namespace = false
        }
      }
      
      // Scrape profiles from pods with annotations
      discovery.relabel "profile_pods" {
        targets = discovery.kubernetes.pods.targets
        
        // Only keep pods with profile annotations
        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_cpu_scrape"]
          regex = "true"
          action = "keep"
        }
        
        // Set the profile port
        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_profiles_grafana_com_cpu_port"]
          target_label = "__profile_port__"
        }
        
        // Set pod labels
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label = "namespace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label = "pod"
        }
      }
      
      // Collect profiles and send to Pyroscope
      pyroscope.scrape "kubernetes" {
        targets = discovery.relabel.profile_pods.output
        
        profiling_config {
          profile.process_cpu {
            enabled = true
            path = "/debug/pprof/profile"
          }
          profile.memory {
            enabled = true
            path = "/debug/pprof/heap"  
          }
          profile.goroutine {
            enabled = true
            path = "/debug/pprof/goroutine"
          }
        }
        
        forward_to = [pyroscope.write.profiles.receiver]
      }
      
      // Write profiles to Pyroscope
      pyroscope.write "profiles" {
        endpoint {
          url = "http://pyroscope.observability.svc.home-hk1-cluster.orbb.li:4040"
        }
      }

# Deployment configuration
controller:
  type: deployment
  replicas: 1

# Service
service:
  enabled: true
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP

# RBAC
rbac:
  create: true

# Service Account
serviceAccount:
  create: true
  name: alloy

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi