apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: networking
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: home-hk1-cluster-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    # Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted
    no-autoupdate: true
    # Ingress rules for routing traffic from cloudflared to local services
    ingress:
    - hostname: mgroupav.orbb.li
      service: http://tube-jellyfin.mgroup.svc.cluster.local
      originRequest:
        noTLSVerify: true
    - hostname: av.orbb.li
      service: http://tube-jellyfin.mgroup.svc.cluster.local
      originRequest:
        noTLSVerify: true
    - hostname: keycloak-lab.orbb.li
      service: http://keycloak.iam.svc.cluster.local
      originRequest:
        noTLSVerify: true
    - hostname: grafana-lab.orbb.li
      service: http://kube-prometheus-stack-grafana.observability.svc.cluster.local
      originRequest:
        noTLSVerify: true
    - hostname: argocd-gitops.home-hk1-cluster.orbb.li
      service: http://argocd-server.gitops.svc.cluster.local
      originRequest:
        noTLSVerify: true
    # Default route
    - service: http_status:404