apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

# Helm chart as generator
helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    version: 1.23.3
    releaseName: tempo
    namespace: observability
    valuesFile: values.yaml