# Grafana Tempo Helm Chart Values
# Minimal configuration - using chart defaults

# Enable persistence
persistence:
  enabled: true
  storageClassName: k8s-csi
  size: 10Gi

# Basic resource limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true