apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: iam
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: keycloak
type: Opaque
stringData:
  username: keycloak
  # Password will be generated and patched by Ansible
  password: WILL_BE_GENERATED