apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iam

resources:
# Namespace needs to exist first
- namespace.yaml
# These will be placeholders - Ansible will patch with real values
- postgres-secret.yaml
- keycloak-db-secret.yaml