apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: iam
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: keycloak
type: Opaque
stringData:
  POSTGRES_USER: keycloak
  POSTGRES_DB: keycloak
  # Password will be generated and patched by Ansible
  POSTGRES_PASSWORD: WILL_BE_GENERATED