apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iam

resources:
# Realm configurations
- orbb-li-realm.yaml
# Note: master-realm-user.yaml won't work for modifying master realm
# but we include it for documentation purposes
#- master-realm-user.yaml