---
- name: Mount disks on worker nodes
  hosts: k8s_masters
  become: true
  tasks:
    - name: Create mount points
      file:
        path: "{{ item.mountpoint }}"
        state: directory
        mode: '0755'
      when: disk is defined
      with_items: "{{ disk | default([]) }}"

    - name: Mount disks
      mount:
        path: "{{ item.mountpoint }}"
        src: "{{ item.device }}"
        fstype: ext4
        state: mounted
      when: disk is defined
      with_items: "{{ disk | default([]) }}"

    - name: Install NFS server
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        regexp: "^{{ item.mountpoint }}"
        line: "{{ item.mountpoint }} *(rw,sync,no_subtree_check,no_root_squash)"
        state: present
      when: disk is defined
      with_items: "{{ disk | default([]) }}"

    - name: Restart NFS server
      systemd:
        name: nfs-server
        state: restarted
        enabled: yes
