shared_drive:
  hosts:
    sd1:
      ansible_host: 192.168.86.31

k8s_masters:
  hosts:
    home-hk1-pi1:
      ansible_host: 192.168.86.41
      mac: 11:22:33:44:55:66
      serial: abcd1234
      disk:
        - device: /dev/nvme0n1p1
          mountpoint: /srv/k8s
    home-hk1-pi2:
      ansible_host: 192.168.86.43
      mac: aa:bb:cc:dd:ee:ff
      serial: 1234abcd

on_prem:
  vars:
    ansible_user: o
    tailscale_oauth_client_id: "oauthid"
    tailscale_oauth_client_secret: "oauthpw"
    tailscale_operator_hostname: "home-hk1-cluster-tsop"
  children:
    shared_drive:
    k8s_masters: