# App of Apps for Grafana Components Stack
# This parent application manages Tempo, Pyroscope, and Loki
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-components
  namespace: gitops
  labels:
    app.kubernetes.io/name: grafana-components
    app.kubernetes.io/part-of: observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  
  source:
    repoURL: https://github.com/orbli/homelab.git
    targetRevision: master
    path: kubernetes/argocd/grafana-components
    kustomize: {}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - Replace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  info:
    - name: 'Components'
      value: 'Tempo (Tracing), Pyroscope (Profiling), Loki (Logging)'
    - name: 'Description'  
      value: 'Grafana observability components for logs, traces, and profiles'